/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { WebhookCreateNestedManyWithoutAppModelsInput } from "./WebhookCreateNestedManyWithoutAppModelsInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { CredentialCreateNestedManyWithoutAppModelsInput } from "./CredentialCreateNestedManyWithoutAppModelsInput";
import { ApiKeyCreateNestedManyWithoutAppModelsInput } from "./ApiKeyCreateNestedManyWithoutAppModelsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumAppModelCategories } from "./EnumAppModelCategories";

@InputType()
class AppModelCreateInput {
  @ApiProperty({
    required: false,
    type: () => WebhookCreateNestedManyWithoutAppModelsInput,
  })
  @ValidateNested()
  @Type(() => WebhookCreateNestedManyWithoutAppModelsInput)
  @IsOptional()
  @Field(() => WebhookCreateNestedManyWithoutAppModelsInput, {
    nullable: true,
  })
  webhook?: WebhookCreateNestedManyWithoutAppModelsInput;

  @ApiProperty({
    required: false,
    type: () => CredentialCreateNestedManyWithoutAppModelsInput,
  })
  @ValidateNested()
  @Type(() => CredentialCreateNestedManyWithoutAppModelsInput)
  @IsOptional()
  @Field(() => CredentialCreateNestedManyWithoutAppModelsInput, {
    nullable: true,
  })
  credentials?: CredentialCreateNestedManyWithoutAppModelsInput;

  @ApiProperty({
    required: false,
    type: () => ApiKeyCreateNestedManyWithoutAppModelsInput,
  })
  @ValidateNested()
  @Type(() => ApiKeyCreateNestedManyWithoutAppModelsInput)
  @IsOptional()
  @Field(() => ApiKeyCreateNestedManyWithoutAppModelsInput, {
    nullable: true,
  })
  apiKey?: ApiKeyCreateNestedManyWithoutAppModelsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  dirName!: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  keys?: InputJsonValue;

  @ApiProperty({
    required: true,
    enum: EnumAppModelCategories,
    isArray: true,
  })
  @IsEnum(EnumAppModelCategories, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumAppModelCategories], {
    nullable: true,
  })
  categories?: Array<
    "calendar" | "messaging" | "other" | "payment" | "video" | "web3"
  >;
}

export { AppModelCreateInput as AppModelCreateInput };
